name: Closed Issue Message
on:
    issues:
        types: [closed]
jobs:
    auto_comment:
        permissions:
            # Required to checkout the code
            contents: read
            # Required to put a comment into the pull-request
            pull-requests: write

        runs-on: ubuntu-latest
        steps:
            - uses: aws-actions/closed-issue-message@v2
              with:
                  # These inputs are both required
                  repo-token: '${{ secrets.GITHUB_TOKEN }}'
                  message: |
                      ### ⚠️COMMENT VISIBILITY WARNING⚠️
                      Comments on closed issues are hard for our team to see.
                      If you need more assistance, please open a new issue that references this one.
                      If you wish to keep having a conversation with other community members under this issue feel free to do so.
